### ISSUE TITLE
Ubuntu 15 renames node to nodejs

### ISSUE THREAD

**Issue by danbikle** [dchem/node-ibapi-addon#80]
Ubuntu 15 renames node to nodejs.

This causes problems with npm install ibapi

Workaround:
cd /usr/bin
ln -s nodejs node

**Comment by dchem** [comment]
It's the node.js version check at preinstall.sh I will add check for nodejs command as well.

**Comment by dchem** [comment]
@danbikle Can you type in ```node -v``` and tell me the version you see? Is it ```v0.10.25```?

**Comment by dchem** [comment]
For my own record https://github.com/joyent/node/issues/3911 is the reason. The install fails at node-gyp because of namespace issues in debian. I can't fix this on my end.

Cleanest solution (if one were to install node.js using debian) is to do ```sudo apt-get install nodejs-legacy``` it sets proper path for node.js.

**Comment by danbikle** [comment]
```
dan@ann15:~/nia/examples $ 
dan@ann15:~/nia/examples $ node --version
v0.10.25
dan@ann15:~/nia/examples $ 
dan@ann15:~/nia/examples $ 
dan@ann15:~/nia/examples $ nodejs --version
v0.10.25
dan@ann15:~/nia/examples $ 
dan@ann15:~/nia/examples $ ll /usr/bin/node*
lrwxrwxrwx 1 root root       6 Apr 30 04:27 /usr/bin/node -> nodejs*
lrwxrwxrwx 1 root root      33 Apr 26  2014 /usr/bin/node-gyp -> ../share/node-gyp/bin/node-gyp.js*
-rwxr-xr-x 1 root root 1462424 Mar 27  2014 /usr/bin/nodejs*
dan@ann15:~/nia/examples $ 
dan@ann15:~/nia/examples $ 
```
